# Programa Ingenias+ Data Science

# Nueva sección

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

In [ ]:
# 1. Crear un arreglo de ceros de longitud 12
array1 = np.zeros(12)

In [ ]:
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
##Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array2 = np.zeros(10)
array2[4] = 10
print(array2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
##Crear un arreglo que tenga los números del 10 al 49
array3 = np.arange(10, 50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 4. Crear una arreglo 2D de shape (3, 3) que tenga los números del 0 al 8
array4 = np.arange(9).reshape(3, 3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
random_array = np.random.rand(100)
mean = np.mean(random_array)
variance = np.var(random_array)
print(mean)
print(variance)

0.48874097826183543
0.08073040354417339


In [ ]:
# 6. Calcular la media de un arreglo usando np.sum
array_mean = np.array([1, 2, 3, 4, 5])
mean_calculated = np.sum(array_mean) / array_mean.size
print(mean_calculated)

3.0


In [ ]:
## Calcular la varianza de un arreglo usando np.sum y np.mean
array_variance = np.array([1, 2, 3, 4, 5])
mean_array = np.mean(array_variance)
variance_calculated = np.sum((array_variance - mean_array) ** 2) / array_variance.size
print(array_variance)
print(mean_array)
print(variance_calculated)

[1 2 3 4 5]
3.0
2.0


In [ ]:
# 8. Crear un array de números aleatorios usando np.random.randn
random_array_np = np.random.randn(10)
print(random_array_np)

[ 1.52217191  0.74827581  0.20345547  0.81274597 -1.1887348  -1.96492949
 -0.22537793  0.71790259  1.35141846 -1.28749595]


In [ ]:

# Imprimir los resultados
print("1. Arreglo de ceros:", array1)
print("2. Arreglo con un 10 en la posición 5:", array2)
print("3. Arreglo con números del 10 al 49:", array3)
print("4. Arreglo 2D del 0 al 8:", array4)
print("5. Media del arreglo de números aleatorios:", mean)
print("   Varianza del arreglo de números aleatorios:", variance)
print("6. Media del arreglo usando np.sum:", mean_calculated)
print("7. Varianza del arreglo usando np.sum y np.mean:", variance_calculated)
print("8. Arreglo de números aleatorios con np.random.randn:", random_array_np)







1. Arreglo de ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Arreglo con un 10 en la posición 5: [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]
3. Arreglo con números del 10 al 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
4. Arreglo 2D del 0 al 8: [[0 1 2]
 [3 4 5]
 [6 7 8]]
5. Media del arreglo de números aleatorios: 0.48874097826183543
   Varianza del arreglo de números aleatorios: 0.08073040354417339
6. Media del arreglo usando np.sum: 3.0
7. Varianza del arreglo usando np.sum y np.mean: 2.0
8. Arreglo de números aleatorios con np.random.randn: [ 1.52217191  0.74827581  0.20345547  0.81274597 -1.1887348  -1.96492949
 -0.22537793  0.71790259  1.35141846 -1.28749595]
